import { Link, useRouterState } from "@tanstack/react-router";
import { useEffect, useMemo, useState, type ReactNode } from "react";
import {
  Bell, Building2, CalendarClock, Camera, ChevronRight, CircleUserRound, Cloud, CloudOff,
  Database, FileCheck2, FileText, Fullscreen, Gauge, LogOut, MapPin, Menu, Radio, Search,
  Moon, Settings, ShieldCheck, Shuffle, SlidersHorizontal, Sun, Timer, TriangleAlert, UserRound, Wifi,
  X, CheckCircle2, Clock3, Crosshair, Download, RefreshCw
} from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Progress } from "@/components/ui/progress";
import { Switch } from "@/components/ui/switch";
import { cn } from "@/lib/utils";
import type { Inspection, Status, SyncStatus } from "@/lib/demo-data";
import type { PortalSession } from "@/lib/auth";

const nav = [
  ["/", "Dashboard", Gauge], ["/organizations", "Organizations", Building2], ["/inspections", "Inspections", FileCheck2],
  ["/random-schedule", "Random Schedule", Shuffle], ["/live-monitoring", "Live Monitoring", Radio],
  ["/inspection-records", "Inspection Records", Database], ["/evidence-verification", "Evidence Verification", ShieldCheck],
  ["/offline-sync", "Offline Sync", Cloud], ["/reports", "Reports", FileText], ["/settings", "Settings", Settings],
] as const;

export function Logo({ compact = false }: { compact?: boolean }) {
  return <div className="flex min-w-0 items-center gap-3"><img src="/logo.jpg" alt="Satark Drishti" className="size-10 shrink-0 rounded-lg border bg-white object-contain shadow-brand"/>{!compact && <div className="min-w-0"><div className="truncate font-display text-[15px] font-bold leading-tight text-sidebar-foreground">SATARK DRISHTI</div><div className="text-[10px] font-semibold uppercase tracking-[0.18em] text-sidebar-muted">Verify. Monitor. Trust.</div></div>}</div>;
}

function ThemeToggle({ checked, onCheckedChange }: { checked: boolean; onCheckedChange: (checked: boolean) => void }) {
  return <div className="flex items-center justify-between gap-3 px-3 py-3"><div className="flex items-center gap-3 text-sm font-medium text-sidebar-foreground">{checked ? <Moon className="size-4"/> : <Sun className="size-4"/>}<span>Dark mode</span></div><Switch checked={checked} onCheckedChange={onCheckedChange} aria-label="Dark mode"/></div>;
}

export function PortalShell({ children, session, onLogout }: { children: ReactNode; session: PortalSession; onLogout: () => void }) {
  const [open, setOpen] = useState(false);
  const [isDark, setIsDark] = useState(false);
  const pathname = useRouterState({ select: (state) => state.location.pathname });
  useEffect(() => {
    const dark = window.localStorage.getItem("satark-theme") === "dark";
    setIsDark(dark);
    document.documentElement.classList.toggle("dark", dark);
  }, []);
  const handleThemeChange = (dark: boolean) => {
    setIsDark(dark);
    document.documentElement.classList.toggle("dark", dark);
    window.localStorage.setItem("satark-theme", dark ? "dark" : "light");
  };
  return <div className="min-h-screen bg-background text-foreground">
    <aside className="fixed inset-y-0 left-0 z-40 hidden w-64 flex-col border-r border-sidebar-border bg-sidebar lg:flex">
      <div className="border-b border-sidebar-border px-5 py-5"><Logo/><div className="mt-4 rounded-md border border-sidebar-border bg-sidebar-accent px-3 py-2 text-xs font-medium text-sidebar-muted">Authority Portal</div></div>
      <nav className="flex-1 space-y-1 overflow-y-auto p-3">{nav.map(([to,label,Icon]) => <Link key={to} to={to} activeOptions={{ exact: to === "/" }} className={cn("group flex items-center gap-3 rounded-md px-3 py-2.5 text-[13px] font-medium text-sidebar-muted transition-colors hover:bg-sidebar-accent hover:text-sidebar-foreground", (to === "/" ? pathname === "/" : pathname.startsWith(to)) && "bg-sidebar-primary text-sidebar-primary-foreground shadow-sm")}><Icon className="size-[18px] shrink-0"/><span>{label}</span></Link>)}</nav>
      <div className="border-t border-sidebar-border px-1"><ThemeToggle checked={isDark} onCheckedChange={handleThemeChange}/></div>
      <div className="border-t border-sidebar-border p-4"><div className="flex items-center gap-3"><div className="grid size-9 place-items-center rounded-full bg-sidebar-accent text-sidebar-foreground"><UserRound className="size-4"/></div><div className="min-w-0"><p className="truncate text-xs font-semibold text-sidebar-foreground">{session.role}</p><p className="truncate text-[11px] text-sidebar-muted">{session.email}</p></div></div></div>
    </aside>
    {open && <div className="fixed inset-0 z-50 bg-overlay lg:hidden" onClick={() => setOpen(false)}><aside className="flex h-full w-[280px] flex-col bg-sidebar p-4" onClick={(event) => event.stopPropagation()}><div className="mb-6 flex items-center justify-between"><Logo/><Button variant="ghost" size="icon" onClick={() => setOpen(false)} aria-label="Close navigation"><X/></Button></div><nav className="flex-1 space-y-1">{nav.map(([to,label,Icon]) => <Link key={to} to={to} onClick={() => setOpen(false)} className="flex items-center gap-3 rounded-md px-3 py-3 text-sm text-sidebar-muted hover:bg-sidebar-accent hover:text-sidebar-foreground"><Icon className="size-5"/>{label}</Link>)}</nav><div className="border-t border-sidebar-border"><ThemeToggle checked={isDark} onCheckedChange={handleThemeChange}/></div></aside></div>}
    <div className="lg:pl-64">
      <header className="sticky top-0 z-30 grid h-16 grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-3 border-b bg-background/95 px-4 backdrop-blur md:px-7"><Button variant="ghost" size="icon" className="lg:hidden" onClick={() => setOpen(true)} aria-label="Open navigation"><Menu/></Button><div className="relative hidden max-w-lg md:block"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><input className="h-9 w-full rounded-md border bg-muted/50 pl-9 pr-3 text-sm outline-none transition focus:border-ring focus:ring-2 focus:ring-ring/20" placeholder="Search inspections, organizations, evidence..."/></div><div className="flex items-center gap-2 md:hidden"><Logo compact/><span className="text-xs font-semibold text-muted-foreground">Authority Portal</span></div><div className="flex items-center gap-2"><Button variant="ghost" size="icon" aria-label="Notifications" onClick={() => toast.info("No new critical alerts")} className="relative"><Bell/><span className="absolute right-1.5 top-1.5 size-2 rounded-full bg-warning ring-2 ring-background"/></Button><div className="hidden h-8 w-px bg-border sm:block"/><div className="hidden items-center gap-2 sm:flex"><div className="grid size-8 place-items-center rounded-full bg-primary text-primary-foreground"><CircleUserRound className="size-4"/></div><div><p className="text-xs font-semibold">{session.role}</p><p className="text-[10px] text-muted-foreground">{session.email}</p></div></div><Button variant="ghost" size="sm" onClick={onLogout} aria-label="Sign out" className="px-2 sm:px-3"><LogOut/><span className="hidden sm:inline">Sign out</span></Button></div></header>
      <main className="mx-auto max-w-[1600px] px-4 py-6 pb-24 md:px-7 md:py-8 lg:pb-10">{children}</main>
    </div>
    <nav className="fixed inset-x-3 bottom-3 z-40 grid grid-cols-5 rounded-lg border bg-background/95 p-1.5 shadow-xl backdrop-blur lg:hidden">{nav.slice(0,5).map(([to,label,Icon]) => <Link key={to} to={to} activeOptions={{ exact: to === "/" }} className="flex min-w-0 flex-col items-center gap-1 rounded-md px-1 py-2 text-[9px] font-medium text-muted-foreground" activeProps={{className:"bg-accent text-accent-foreground"}}><Icon className="size-4"/><span className="truncate">{label.split(" ")[0]}</span></Link>)}</nav>
  </div>;
}

export function PageHeader({ eyebrow, title, description, actions }: { eyebrow?: string; title: string; description: string; actions?: ReactNode }) {
  return <div className="mb-6 grid grid-cols-[minmax(0,1fr)_auto] items-end gap-4"><div className="min-w-0">{eyebrow && <p className="mb-2 text-xs font-bold uppercase tracking-[0.16em] text-primary">{eyebrow}</p>}<h1 className="font-display text-2xl font-bold tracking-normal md:text-3xl">{title}</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">{description}</p></div>{actions && <div className="shrink-0">{actions}</div>}</div>;
}

export function DemoNote() { return <div className="mb-5 flex items-center gap-2 rounded-md border border-info/20 bg-info-soft px-3 py-2 text-xs text-info"><Database className="size-4 shrink-0"/>Demonstration environment · All records, people, locations and coordinates are fictional.</div>; }

const tone: Record<string,string> = { Verified:"success", Captured:"success", Synced:"info", Pending:"warning", Flagged:"danger", "Outside radius":"danger", "Offline Sync Pending":"warning", Failed:"danger", Online:"success", Offline:"neutral", Completed:"success", Upcoming:"info", Randomized:"random" };
export function StatusBadge({ children, pulse=false }: { children: ReactNode; pulse?: boolean }) { const value=String(children); return <span className={cn("inline-flex items-center gap-1.5 whitespace-nowrap rounded-full px-2.5 py-1 text-[11px] font-bold", `status-${tone[value] ?? "neutral"}`)}>{pulse && <span className="relative flex size-1.5"><span className="absolute inline-flex size-full animate-ping rounded-full bg-current opacity-50"/><span className="relative inline-flex size-1.5 rounded-full bg-current"/></span>}{children}</span>; }

export function StatCard({ label, value, detail, icon: Icon, toneName="primary" }: { label:string; value:string|number; detail:string; icon:any; toneName?:string }) { return <div className="group rounded-lg border bg-card p-4 shadow-card transition duration-200 hover:-translate-y-0.5 hover:shadow-card-hover"><div className="flex items-start justify-between"><div className={cn("grid size-9 place-items-center rounded-md", `stat-${toneName}`)}><Icon className="size-[18px]"/></div><span className="text-[10px] font-bold uppercase tracking-[0.12em] text-muted-foreground">Live summary</span></div><p className="mt-5 text-2xl font-bold tabular-nums">{value}</p><p className="mt-1 text-xs font-semibold">{label}</p><p className="mt-1 text-[11px] text-muted-foreground">{detail}</p></div>; }

const evidenceItems = [[MapPin,"GPS","Within boundary"],[Camera,"Photo","Live capture"],[Timer,"Timestamp","Recorded"],[UserRound,"Inspector","Assigned"],[Building2,"Organization","Matched"],[Cloud,"Sync Status","Synchronized"]] as const;
export function InspectionEvidenceCard({ compact=false, inspection }: { compact?:boolean; inspection?:Inspection }) { return <div className="overflow-hidden rounded-lg border bg-card shadow-card"><div className="flex items-center justify-between border-b bg-evidence px-4 py-3"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-primary">Inspection evidence</p><p className="mt-0.5 text-xs text-muted-foreground">A complete, connected inspection trail</p></div><ShieldCheck className="size-6 text-success"/></div><div className={cn("grid", compact ? "grid-cols-2 sm:grid-cols-3" : "grid-cols-2 md:grid-cols-3 lg:grid-cols-6")}>{evidenceItems.map(([Icon,label,defaultValue]) => { const value = label === "GPS" ? inspection?.gps : label === "Photo" ? inspection?.photo : label === "Inspector" ? inspection?.inspector : label === "Organization" ? inspection?.organization : label === "Sync Status" ? inspection?.sync : undefined; return <div key={label} className="min-w-0 border-b border-r p-3 last:border-r-0 md:border-b-0"><Icon className="mb-2 size-4 text-primary"/><p className="text-[10px] font-bold uppercase tracking-[0.1em] text-muted-foreground">{label}</p><p className="mt-1 truncate text-xs font-semibold">{value ?? defaultValue}</p></div>})}</div></div>; }

export function InspectionTable({ rows, limit }: { rows:Inspection[]; limit?:number }) { const shown=limit?rows.slice(0,limit):rows; return <div className="overflow-hidden rounded-lg border bg-card shadow-card"><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-xs"><thead className="border-b bg-muted/60 text-[10px] uppercase tracking-[0.12em] text-muted-foreground"><tr>{["Inspection ID","Organization","Inspector","Date & time","GPS","Photo","Verification","Sync","Action"].map(h=><th key={h} className="px-4 py-3 font-bold">{h}</th>)}</tr></thead><tbody>{shown.map(row=><tr key={row.id} className="border-b last:border-0 hover:bg-muted/35"><td className="px-4 py-4 font-mono text-[11px] font-semibold text-primary">{row.id}</td><td className="px-4 py-4 font-semibold">{row.organization}</td><td className="px-4 py-4 text-muted-foreground">{row.inspector}</td><td className="px-4 py-4"><p>{row.date}</p><p className="text-muted-foreground">{row.time}</p></td><td className="px-4 py-4"><StatusBadge>{row.gps}</StatusBadge></td><td className="px-4 py-4"><StatusBadge>{row.photo}</StatusBadge></td><td className="px-4 py-4"><StatusBadge>{row.status}</StatusBadge></td><td className="px-4 py-4"><StatusBadge>{row.sync}</StatusBadge></td><td className="px-4 py-4"><Button variant="outline" size="sm" asChild><Link to="/inspections/$inspectionId" params={{inspectionId:row.id}}>View details<ChevronRight/></Link></Button></td></tr>)}</tbody></table></div></div>; }

export function Filters({ placeholder="Search records..." }: { placeholder?:string }) { return <div className="mb-4 grid gap-3 sm:grid-cols-[minmax(0,1fr)_auto]"><div className="relative"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><input placeholder={placeholder} className="h-10 w-full rounded-md border bg-card pl-9 pr-3 text-sm outline-none focus:ring-2 focus:ring-ring/20"/></div><Button variant="outline"><SlidersHorizontal/>Filters</Button></div>; }

export function GPSMap({ flagged=false }: { flagged?:boolean }) { return <div className="relative min-h-[310px] overflow-hidden rounded-lg border bg-map shadow-card"><div className="map-grid absolute inset-0"/><div className="absolute left-[20%] top-[20%] h-px w-[70%] rotate-12 bg-map-road"/><div className="absolute left-[35%] top-0 h-full w-px -rotate-12 bg-map-road"/><div className="absolute left-[58%] top-1/2 size-40 -translate-x-1/2 -translate-y-1/2 rounded-full border-2 border-dashed border-success/70 bg-success/10"><span className="absolute inset-8 rounded-full border border-success/30"/></div><div className="absolute left-[58%] top-1/2 grid size-10 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full bg-primary text-primary-foreground shadow-brand"><Building2 className="size-5"/></div><div className={cn("absolute grid size-8 place-items-center rounded-full text-primary-foreground shadow-lg", flagged?"left-[78%] top-[28%] bg-destructive":"left-[62%] top-[43%] bg-success")}><Crosshair className="size-4"/></div><div className="absolute bottom-3 left-3 rounded-md border bg-background/95 px-3 py-2 shadow-sm"><p className="text-[10px] font-bold uppercase text-muted-foreground">Verification boundary</p><p className="mt-0.5 text-xs font-semibold">Authorized radius · 100 metres</p></div></div>; }

export function Section({ title, description, action, children, className }: { title:string; description?:string; action?:ReactNode; children:ReactNode; className?:string }) { return <section className={cn("mb-6",className)}><div className="mb-4 grid grid-cols-[minmax(0,1fr)_auto] items-end gap-3"><div><h2 className="font-display text-lg font-bold">{title}</h2>{description&&<p className="mt-1 text-xs leading-5 text-muted-foreground">{description}</p>}</div>{action}</div>{children}</section>; }

export function PhotoViewer({ image, inspection }: { image:string; inspection:Inspection }) { return <Dialog><div className="overflow-hidden rounded-lg border bg-card shadow-card"><div className="relative aspect-[16/9] overflow-hidden bg-muted"><img src={image} alt="Demonstration inspection evidence captured at a community learning center" className="h-full w-full object-cover" width={1280} height={800}/><div className="absolute left-3 top-3"><StatusBadge pulse>LIVE CAPTURE</StatusBadge></div><DialogTrigger asChild><Button size="icon" variant="secondary" className="absolute right-3 top-3" aria-label="View photo fullscreen"><Fullscreen/></Button></DialogTrigger></div><div className="grid grid-cols-2 gap-4 p-4 text-xs"><div><p className="text-muted-foreground">Captured during inspection</p><p className="mt-1 font-semibold">{inspection.date} · {inspection.time}</p></div><div><p className="text-muted-foreground">Evidence ID</p><p className="mt-1 font-mono font-semibold">{inspection.evidenceId}</p></div><div className="col-span-2"><p className="text-muted-foreground">GPS coordinates</p><p className="mt-1 font-semibold">{inspection.coordinates}</p></div></div></div><DialogContent className="max-w-5xl p-2"><DialogHeader className="sr-only"><DialogTitle>Inspection photo evidence</DialogTitle><DialogDescription>Fullscreen view of demonstration inspection evidence.</DialogDescription></DialogHeader><img src={image} alt="Fullscreen demonstration inspection evidence" width={1280} height={800} className="max-h-[82vh] w-full rounded-md object-contain"/></DialogContent></Dialog>; }

export function SyncPanel() { const [progress,setProgress]=useState(64); const sync=()=>{setProgress(82); setTimeout(()=>{setProgress(100);toast.success("Synchronization Complete ✓")},700)}; return <div className="rounded-lg border bg-card p-5 shadow-card"><div className="flex items-start justify-between"><div><p className="text-sm font-bold">3 inspections waiting for synchronization</p><p className="mt-1 text-xs text-muted-foreground">Encrypted records will upload when connection is stable.</p></div><Wifi className="size-5 text-success"/></div><div className="mt-5"><div className="mb-2 flex justify-between text-xs"><span className="font-semibold">Synchronization progress</span><span className="font-bold tabular-nums">{progress}%</span></div><Progress value={progress}/></div><Button className="mt-5" onClick={sync} disabled={progress===100}>{progress===100?<CheckCircle2/>:<RefreshCw/>}{progress===100?"Synchronization Complete":"Sync now"}</Button></div>; }

export const Icons = { Building2, CalendarClock, Camera, CloudOff, FileCheck2, ShieldCheck, TriangleAlert, Shuffle, Radio, Wifi, Clock3, Download };
export type { Status, SyncStatus };
