/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EvidenceVerificationRouteImport } from './routes/evidence-verification'
import { Route as InspectionRecordsRouteImport } from './routes/inspection-records'
import { Route as InspectionsRouteImport } from './routes/inspections'
import { Route as LiveMonitoringRouteImport } from './routes/live-monitoring'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OfflineSyncRouteImport } from './routes/offline-sync'
import { Route as OrganizationsRouteImport } from './routes/organizations'
import { Route as RandomScheduleRouteImport } from './routes/random-schedule'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as InspectionsIndexRouteImport } from './routes/inspections.index'
import { Route as InspectionsInspectionIdRouteImport } from './routes/inspections.$inspectionId'
import { Route as OrganizationsIndexRouteImport } from './routes/organizations.index'
import { Route as OrganizationsOrganizationIdRouteImport } from './routes/organizations.$organizationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceVerificationRoute = EvidenceVerificationRouteImport.update({
  id: '/evidence-verification',
  path: '/evidence-verification',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectionRecordsRoute = InspectionRecordsRouteImport.update({
  id: '/inspection-records',
  path: '/inspection-records',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectionsRoute = InspectionsRouteImport.update({
  id: '/inspections',
  path: '/inspections',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveMonitoringRoute = LiveMonitoringRouteImport.update({
  id: '/live-monitoring',
  path: '/live-monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineSyncRoute = OfflineSyncRouteImport.update({
  id: '/offline-sync',
  path: '/offline-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsRoute = OrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const RandomScheduleRoute = RandomScheduleRouteImport.update({
  id: '/random-schedule',
  path: '/random-schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectionsIndexRoute = InspectionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InspectionsRoute,
} as any)
const InspectionsInspectionIdRoute = InspectionsInspectionIdRouteImport.update({
  id: '/$inspectionId',
  path: '/$inspectionId',
  getParentRoute: () => InspectionsRoute,
} as any)
const OrganizationsIndexRoute = OrganizationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrganizationsRoute,
} as any)
const OrganizationsOrganizationIdRoute =
  OrganizationsOrganizationIdRouteImport.update({
    id: '/$organizationId',
    path: '/$organizationId',
    getParentRoute: () => OrganizationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/evidence-verification': typeof EvidenceVerificationRoute
  '/inspection-records': typeof InspectionRecordsRoute
  '/inspections': typeof InspectionsRouteWithChildren
  '/live-monitoring': typeof LiveMonitoringRoute
  '/login': typeof LoginRoute
  '/offline-sync': typeof OfflineSyncRoute
  '/organizations': typeof OrganizationsRouteWithChildren
  '/random-schedule': typeof RandomScheduleRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/inspections/$inspectionId': typeof InspectionsInspectionIdRoute
  '/organizations/$organizationId': typeof OrganizationsOrganizationIdRoute
  '/inspections/': typeof InspectionsIndexRoute
  '/organizations/': typeof OrganizationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/evidence-verification': typeof EvidenceVerificationRoute
  '/inspection-records': typeof InspectionRecordsRoute
  '/live-monitoring': typeof LiveMonitoringRoute
  '/login': typeof LoginRoute
  '/offline-sync': typeof OfflineSyncRoute
  '/random-schedule': typeof RandomScheduleRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/inspections/$inspectionId': typeof InspectionsInspectionIdRoute
  '/organizations/$organizationId': typeof OrganizationsOrganizationIdRoute
  '/inspections': typeof InspectionsIndexRoute
  '/organizations': typeof OrganizationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/evidence-verification': typeof EvidenceVerificationRoute
  '/inspection-records': typeof InspectionRecordsRoute
  '/inspections': typeof InspectionsRouteWithChildren
  '/live-monitoring': typeof LiveMonitoringRoute
  '/login': typeof LoginRoute
  '/offline-sync': typeof OfflineSyncRoute
  '/organizations': typeof OrganizationsRouteWithChildren
  '/random-schedule': typeof RandomScheduleRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/inspections/$inspectionId': typeof InspectionsInspectionIdRoute
  '/organizations/$organizationId': typeof OrganizationsOrganizationIdRoute
  '/inspections/': typeof InspectionsIndexRoute
  '/organizations/': typeof OrganizationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/evidence-verification'
    | '/inspection-records'
    | '/inspections'
    | '/live-monitoring'
    | '/login'
    | '/offline-sync'
    | '/organizations'
    | '/random-schedule'
    | '/reports'
    | '/settings'
    | '/inspections/$inspectionId'
    | '/organizations/$organizationId'
    | '/inspections/'
    | '/organizations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/evidence-verification'
    | '/inspection-records'
    | '/live-monitoring'
    | '/login'
    | '/offline-sync'
    | '/random-schedule'
    | '/reports'
    | '/settings'
    | '/inspections/$inspectionId'
    | '/organizations/$organizationId'
    | '/inspections'
    | '/organizations'
  id:
    | '__root__'
    | '/'
    | '/evidence-verification'
    | '/inspection-records'
    | '/inspections'
    | '/live-monitoring'
    | '/login'
    | '/offline-sync'
    | '/organizations'
    | '/random-schedule'
    | '/reports'
    | '/settings'
    | '/inspections/$inspectionId'
    | '/organizations/$organizationId'
    | '/inspections/'
    | '/organizations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EvidenceVerificationRoute: typeof EvidenceVerificationRoute
  InspectionRecordsRoute: typeof InspectionRecordsRoute
  InspectionsRoute: typeof InspectionsRouteWithChildren
  LiveMonitoringRoute: typeof LiveMonitoringRoute
  LoginRoute: typeof LoginRoute
  OfflineSyncRoute: typeof OfflineSyncRoute
  OrganizationsRoute: typeof OrganizationsRouteWithChildren
  RandomScheduleRoute: typeof RandomScheduleRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence-verification': {
      id: '/evidence-verification'
      path: '/evidence-verification'
      fullPath: '/evidence-verification'
      preLoaderRoute: typeof EvidenceVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspection-records': {
      id: '/inspection-records'
      path: '/inspection-records'
      fullPath: '/inspection-records'
      preLoaderRoute: typeof InspectionRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspections': {
      id: '/inspections'
      path: '/inspections'
      fullPath: '/inspections'
      preLoaderRoute: typeof InspectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-monitoring': {
      id: '/live-monitoring'
      path: '/live-monitoring'
      fullPath: '/live-monitoring'
      preLoaderRoute: typeof LiveMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline-sync': {
      id: '/offline-sync'
      path: '/offline-sync'
      fullPath: '/offline-sync'
      preLoaderRoute: typeof OfflineSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations': {
      id: '/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/random-schedule': {
      id: '/random-schedule'
      path: '/random-schedule'
      fullPath: '/random-schedule'
      preLoaderRoute: typeof RandomScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspections/': {
      id: '/inspections/'
      path: '/'
      fullPath: '/inspections/'
      preLoaderRoute: typeof InspectionsIndexRouteImport
      parentRoute: typeof InspectionsRoute
    }
    '/inspections/$inspectionId': {
      id: '/inspections/$inspectionId'
      path: '/$inspectionId'
      fullPath: '/inspections/$inspectionId'
      preLoaderRoute: typeof InspectionsInspectionIdRouteImport
      parentRoute: typeof InspectionsRoute
    }
    '/organizations/': {
      id: '/organizations/'
      path: '/'
      fullPath: '/organizations/'
      preLoaderRoute: typeof OrganizationsIndexRouteImport
      parentRoute: typeof OrganizationsRoute
    }
    '/organizations/$organizationId': {
      id: '/organizations/$organizationId'
      path: '/$organizationId'
      fullPath: '/organizations/$organizationId'
      preLoaderRoute: typeof OrganizationsOrganizationIdRouteImport
      parentRoute: typeof OrganizationsRoute
    }
  }
}

interface InspectionsRouteChildren {
  InspectionsInspectionIdRoute: typeof InspectionsInspectionIdRoute
  InspectionsIndexRoute: typeof InspectionsIndexRoute
}

const InspectionsRouteChildren: InspectionsRouteChildren = {
  InspectionsInspectionIdRoute: InspectionsInspectionIdRoute,
  InspectionsIndexRoute: InspectionsIndexRoute,
}

const InspectionsRouteWithChildren = InspectionsRoute._addFileChildren(
  InspectionsRouteChildren,
)

interface OrganizationsRouteChildren {
  OrganizationsOrganizationIdRoute: typeof OrganizationsOrganizationIdRoute
  OrganizationsIndexRoute: typeof OrganizationsIndexRoute
}

const OrganizationsRouteChildren: OrganizationsRouteChildren = {
  OrganizationsOrganizationIdRoute: OrganizationsOrganizationIdRoute,
  OrganizationsIndexRoute: OrganizationsIndexRoute,
}

const OrganizationsRouteWithChildren = OrganizationsRoute._addFileChildren(
  OrganizationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EvidenceVerificationRoute: EvidenceVerificationRoute,
  InspectionRecordsRoute: InspectionRecordsRoute,
  InspectionsRoute: InspectionsRouteWithChildren,
  LiveMonitoringRoute: LiveMonitoringRoute,
  LoginRoute: LoginRoute,
  OfflineSyncRoute: OfflineSyncRoute,
  OrganizationsRoute: OrganizationsRouteWithChildren,
  RandomScheduleRoute: RandomScheduleRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
